.TH "Board.h" 3 "Mon Jan 13 2020" "Version 1.0" "copter_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Board.h
.SH SYNOPSIS
.br
.PP
\fC#include 'EK_TM4C1294XL\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBoard_initEMAC\fP   \fBEK_TM4C1294XL_initEMAC\fP"
.br
.ti -1c
.RI "#define \fBBoard_initGeneral\fP   \fBEK_TM4C1294XL_initGeneral\fP"
.br
.ti -1c
.RI "#define \fBBoard_initGPIO\fP   \fBEK_TM4C1294XL_initGPIO\fP"
.br
.ti -1c
.RI "#define \fBBoard_initCAN\fP   \fBEK_TM4C1294XL_initCAN\fP"
.br
.ti -1c
.RI "#define \fBBoard_initI2C\fP   \fBEK_TM4C1294XL_initI2C\fP"
.br
.ti -1c
.RI "#define \fBBoard_initSDSPI\fP   \fBEK_TM4C1294XL_initSDSPI\fP"
.br
.ti -1c
.RI "#define \fBBoard_initSPI\fP   \fBEK_TM4C1294XL_initSPI\fP"
.br
.ti -1c
.RI "#define \fBBoard_initUART\fP   \fBEK_TM4C1294XL_initUART\fP"
.br
.ti -1c
.RI "#define \fBBoard_initUSB\fP   \fBEK_TM4C1294XL_initUSB\fP"
.br
.ti -1c
.RI "#define \fBBoard_initUSBMSCHFatFs\fP   \fBEK_TM4C1294XL_initUSBMSCHFatFs\fP"
.br
.ti -1c
.RI "#define \fBBoard_initWatchdog\fP   \fBEK_TM4C1294XL_initWatchdog\fP"
.br
.ti -1c
.RI "#define \fBBoard_initWiFi\fP   \fBEK_TM4C1294XL_initWiFi\fP"
.br
.ti -1c
.RI "#define \fBBoard_LED_ON\fP   \fBEK_TM4C1294XL_LED_ON\fP"
.br
.ti -1c
.RI "#define \fBBoard_LED_OFF\fP   \fBEK_TM4C1294XL_LED_OFF\fP"
.br
.ti -1c
.RI "#define \fBBoard_LED0\fP   \fBEK_TM4C1294XL_D1\fP"
.br
.ti -1c
.RI "#define \fBBoard_LED1\fP   \fBEK_TM4C1294XL_D2\fP"
.br
.ti -1c
.RI "#define \fBBoard_LED2\fP   \fBEK_TM4C1294XL_D2\fP"
.br
.ti -1c
.RI "#define \fBBoard_BUTTON0\fP   \fBEK_TM4C1294XL_USR_SW1\fP"
.br
.ti -1c
.RI "#define \fBBoard_BUTTON1\fP   \fBEK_TM4C1294XL_USR_SW2\fP"
.br
.ti -1c
.RI "#define \fBBoard_EduMIKI_SEL\fP   \fBEK_TM4C1294XL_EDU_SEL\fP"
.br
.ti -1c
.RI "#define \fBBoard_I2C0\fP   EK_TM4C1294XL_I2C7"
.br
.ti -1c
.RI "#define \fBBoard_I2C1\fP   \fBEK_TM4C1294XL_I2C8\fP"
.br
.ti -1c
.RI "#define \fBBoard_I2C2\fP   EK_TM4C1294XL_I2C0"
.br
.ti -1c
.RI "#define \fBBoard_I2C3\fP   EK_TM4C1294XL_I2C2"
.br
.ti -1c
.RI "#define \fBBoard_I2C_TMP\fP   EK_TM4C1294XL_I2C7"
.br
.ti -1c
.RI "#define \fBBoard_I2C_NFC\fP   EK_TM4C1294XL_I2C7"
.br
.ti -1c
.RI "#define \fBBoard_I2C_TPL0401\fP   EK_TM4C1294XL_I2C7"
.br
.ti -1c
.RI "#define \fBBoard_SDSPI0\fP   \fBEK_TM4C1294XL_SDSPI0\fP"
.br
.ti -1c
.RI "#define \fBBoard_SDSPI1\fP   \fBEK_TM4C1294XL_SDSPI1\fP"
.br
.ti -1c
.RI "#define \fBBoard_SPI0\fP   \fBEK_TM4C1294XL_SPI2\fP"
.br
.ti -1c
.RI "#define \fBBoard_SPI1\fP   EK_TM4C1294XL_SPI3"
.br
.ti -1c
.RI "#define \fBBoard_SPI_CC3100\fP   \fBEK_TM4C1294XL_SPI2\fP"
.br
.ti -1c
.RI "#define \fBBoard_USBMSCHFatFs0\fP   \fBEK_TM4C1294XL_USBMSCHFatFs0\fP"
.br
.ti -1c
.RI "#define \fBBoard_USBHOST\fP   \fBEK_TM4C1294XL_USBHOST\fP"
.br
.ti -1c
.RI "#define \fBBoard_USBDEVICE\fP   \fBEK_TM4C1294XL_USBDEVICE\fP"
.br
.ti -1c
.RI "#define \fBBoard_UART0\fP   \fBEK_TM4C1294XL_UART0\fP"
.br
.ti -1c
.RI "#define \fBBoard_UART2\fP   EK_TM4C1294XL_UART2"
.br
.ti -1c
.RI "#define \fBBoard_UART6\fP   \fBEK_TM4C1294XL_UART6\fP"
.br
.ti -1c
.RI "#define \fBBoard_UART7\fP   EK_TM4C1294XL_UART7"
.br
.ti -1c
.RI "#define \fBBoard_WATCHDOG0\fP   \fBEK_TM4C1294XL_WATCHDOG0\fP"
.br
.ti -1c
.RI "#define \fBBoard_WIFI\fP   \fBEK_TM4C1294XL_WIFI\fP"
.br
.ti -1c
.RI "#define \fBBoard_gpioCallbacks0\fP   EK_TM4C1294XL_gpioPortJCallbacks"
.br
.ti -1c
.RI "#define \fBBoard_gpioCallbacks1\fP   EK_TM4C1294XL_gpioPortJCallbacks"
.br
.ti -1c
.RI "#define \fBBoard_TMP006_ADDR\fP   (0x40)"
.br
.ti -1c
.RI "#define \fBBoard_RF430CL330_ADDR\fP   (0x28)"
.br
.ti -1c
.RI "#define \fBBoard_TPL0401_ADDR\fP   (0x40)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Board_BUTTON0   \fBEK_TM4C1294XL_USR_SW1\fP"

.PP
Definition at line 60 of file Board\&.h\&.
.SS "#define Board_BUTTON1   \fBEK_TM4C1294XL_USR_SW2\fP"

.PP
Definition at line 61 of file Board\&.h\&.
.SS "#define Board_EduMIKI_SEL   \fBEK_TM4C1294XL_EDU_SEL\fP"

.PP
Definition at line 63 of file Board\&.h\&.
.SS "#define Board_gpioCallbacks0   EK_TM4C1294XL_gpioPortJCallbacks"

.PP
Definition at line 94 of file Board\&.h\&.
.SS "#define Board_gpioCallbacks1   EK_TM4C1294XL_gpioPortJCallbacks"

.PP
Definition at line 95 of file Board\&.h\&.
.SS "#define Board_I2C0   EK_TM4C1294XL_I2C7"

.PP
Definition at line 65 of file Board\&.h\&.
.SS "#define Board_I2C1   \fBEK_TM4C1294XL_I2C8\fP"

.PP
Definition at line 66 of file Board\&.h\&.
.SS "#define Board_I2C2   EK_TM4C1294XL_I2C0"

.PP
Definition at line 67 of file Board\&.h\&.
.SS "#define Board_I2C3   EK_TM4C1294XL_I2C2"

.PP
Definition at line 68 of file Board\&.h\&.
.SS "#define Board_I2C_NFC   EK_TM4C1294XL_I2C7"

.PP
Definition at line 70 of file Board\&.h\&.
.SS "#define Board_I2C_TMP   EK_TM4C1294XL_I2C7"

.PP
Definition at line 69 of file Board\&.h\&.
.SS "#define Board_I2C_TPL0401   EK_TM4C1294XL_I2C7"

.PP
Definition at line 71 of file Board\&.h\&.
.SS "#define Board_initCAN   \fBEK_TM4C1294XL_initCAN\fP"

.PP
Definition at line 45 of file Board\&.h\&.
.SS "#define Board_initEMAC   \fBEK_TM4C1294XL_initEMAC\fP"

.PP
Definition at line 42 of file Board\&.h\&.
.SS "#define Board_initGeneral   \fBEK_TM4C1294XL_initGeneral\fP"

.PP
Definition at line 43 of file Board\&.h\&.
.SS "#define Board_initGPIO   \fBEK_TM4C1294XL_initGPIO\fP"

.PP
Definition at line 44 of file Board\&.h\&.
.SS "#define Board_initI2C   \fBEK_TM4C1294XL_initI2C\fP"

.PP
Definition at line 46 of file Board\&.h\&.
.SS "#define Board_initSDSPI   \fBEK_TM4C1294XL_initSDSPI\fP"

.PP
Definition at line 47 of file Board\&.h\&.
.SS "#define Board_initSPI   \fBEK_TM4C1294XL_initSPI\fP"

.PP
Definition at line 48 of file Board\&.h\&.
.SS "#define Board_initUART   \fBEK_TM4C1294XL_initUART\fP"

.PP
Definition at line 49 of file Board\&.h\&.
.SS "#define Board_initUSB   \fBEK_TM4C1294XL_initUSB\fP"

.PP
Definition at line 50 of file Board\&.h\&.
.SS "#define Board_initUSBMSCHFatFs   \fBEK_TM4C1294XL_initUSBMSCHFatFs\fP"

.PP
Definition at line 51 of file Board\&.h\&.
.SS "#define Board_initWatchdog   \fBEK_TM4C1294XL_initWatchdog\fP"

.PP
Definition at line 52 of file Board\&.h\&.
.SS "#define Board_initWiFi   \fBEK_TM4C1294XL_initWiFi\fP"

.PP
Definition at line 53 of file Board\&.h\&.
.SS "#define Board_LED0   \fBEK_TM4C1294XL_D1\fP"

.PP
Definition at line 57 of file Board\&.h\&.
.SS "#define Board_LED1   \fBEK_TM4C1294XL_D2\fP"

.PP
Definition at line 58 of file Board\&.h\&.
.SS "#define Board_LED2   \fBEK_TM4C1294XL_D2\fP"

.PP
Definition at line 59 of file Board\&.h\&.
.SS "#define Board_LED_OFF   \fBEK_TM4C1294XL_LED_OFF\fP"

.PP
Definition at line 56 of file Board\&.h\&.
.SS "#define Board_LED_ON   \fBEK_TM4C1294XL_LED_ON\fP"

.PP
Definition at line 55 of file Board\&.h\&.
.SS "#define Board_RF430CL330_ADDR   (0x28)"

.PP
Definition at line 99 of file Board\&.h\&.
.SS "#define Board_SDSPI0   \fBEK_TM4C1294XL_SDSPI0\fP"

.PP
Definition at line 73 of file Board\&.h\&.
.SS "#define Board_SDSPI1   \fBEK_TM4C1294XL_SDSPI1\fP"

.PP
Definition at line 74 of file Board\&.h\&.
.SS "#define Board_SPI0   \fBEK_TM4C1294XL_SPI2\fP"

.PP
Definition at line 76 of file Board\&.h\&.
.SS "#define Board_SPI1   EK_TM4C1294XL_SPI3"

.PP
Definition at line 77 of file Board\&.h\&.
.SS "#define Board_SPI_CC3100   \fBEK_TM4C1294XL_SPI2\fP"

.PP
Definition at line 78 of file Board\&.h\&.
.SS "#define Board_TMP006_ADDR   (0x40)"

.PP
Definition at line 98 of file Board\&.h\&.
.SS "#define Board_TPL0401_ADDR   (0x40)"

.PP
Definition at line 100 of file Board\&.h\&.
.SS "#define Board_UART0   \fBEK_TM4C1294XL_UART0\fP"

.PP
Definition at line 85 of file Board\&.h\&.
.SS "#define Board_UART2   EK_TM4C1294XL_UART2"

.PP
Definition at line 86 of file Board\&.h\&.
.SS "#define Board_UART6   \fBEK_TM4C1294XL_UART6\fP"

.PP
Definition at line 87 of file Board\&.h\&.
.SS "#define Board_UART7   EK_TM4C1294XL_UART7"

.PP
Definition at line 88 of file Board\&.h\&.
.SS "#define Board_USBDEVICE   \fBEK_TM4C1294XL_USBDEVICE\fP"

.PP
Definition at line 83 of file Board\&.h\&.
.SS "#define Board_USBHOST   \fBEK_TM4C1294XL_USBHOST\fP"

.PP
Definition at line 82 of file Board\&.h\&.
.SS "#define Board_USBMSCHFatFs0   \fBEK_TM4C1294XL_USBMSCHFatFs0\fP"

.PP
Definition at line 80 of file Board\&.h\&.
.SS "#define Board_WATCHDOG0   \fBEK_TM4C1294XL_WATCHDOG0\fP"

.PP
Definition at line 90 of file Board\&.h\&.
.SS "#define Board_WIFI   \fBEK_TM4C1294XL_WIFI\fP"

.PP
Definition at line 92 of file Board\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copter_project from the source code\&.
