.TH "local_inc Directory Reference" 3 "Mon Jan 13 2020" "Version 1.0" "copter_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
local_inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBoard\&.h\fP"
.br
.ti -1c
.RI "file \fBEK_TM4C1294XL\&.h\fP"
.br
.RI "EK_TM4C1294XL Board Specific APIs\&. "
.ti -1c
.RI "file \fBRN4678\&.h\fP"
.br
.RI "The GPIO setup and data transfer functions for the RN4678 module\&. "
.ti -1c
.RI "file \fBTI_Joystick\&.h\fP"
.br
.RI "Application for getting Joystick data, x y-axis ADC values, accelerometer and converting them to the right values for controlling the quadcopter\&. "
.in -1c
