.TH "raw_rc_frame" 3 "Mon Jan 13 2020" "Version 1.0" "copter_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raw_rc_frame
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TI_Joystick\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBroll\fP"
.br
.ti -1c
.RI "uint16_t \fBpitch\fP"
.br
.ti -1c
.RI "uint16_t \fBthrottle\fP"
.br
.ti -1c
.RI "uint16_t \fBazimuth\fP"
.br
.ti -1c
.RI "uint8_t \fBarm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file TI_Joystick\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t raw_rc_frame::arm"

.PP
Definition at line 48 of file TI_Joystick\&.h\&.
.PP
Referenced by arm(), disarm(), and set_flight_controls()\&.
.SS "uint16_t raw_rc_frame::azimuth"
16 bit Range [1000;2000] 
.PP
Definition at line 47 of file TI_Joystick\&.h\&.
.PP
Referenced by joystick_fnx(), and set_flight_controls()\&.
.SS "uint16_t raw_rc_frame::pitch"
16 bit Range [1000;2000] 
.PP
Definition at line 45 of file TI_Joystick\&.h\&.
.PP
Referenced by joystick_fnx(), and set_flight_controls()\&.
.SS "uint16_t raw_rc_frame::roll"
16 bit Range [1000;2000] 
.PP
Definition at line 44 of file TI_Joystick\&.h\&.
.PP
Referenced by joystick_fnx(), and set_flight_controls()\&.
.SS "uint16_t raw_rc_frame::throttle"
16 bit Range [1000;2000] 
.PP
Definition at line 46 of file TI_Joystick\&.h\&.
.PP
Referenced by joystick_fnx(), and set_flight_controls()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for copter_project from the source code\&.
