RN4678.c
NAME
RN4678.c - The GPIO setup and data transfer functions for the RN4678 module.
SYNOPSIS
#include 'RN4678.h'
Functions
void send_pac (char *data, size_t size)
This is used to send Multiwii command to the quadcopter via bluetooth. The header and the command are packed in one packet of bytes. UART Flow Control is used and implemented in the Software for the communication with the RN4678.
void start_com (char *cmd, uint8_t size, uint8_t retsize, char *input)
This is used to send commands to the RN4678 for setting up the communication via bluetooth. UART Flow Control is used and implemented in the Software for the communication with the RN4678. In the initialization phase every command sent to the RN4678 is answered by the module. This answer is read and returned to the calling function.
void RN4678Fxn (UArg arg0, UArg arg1)
This is RN4678 initialization task. This task is managed by the RTOS task manager using the multi-task priority scheduling. A connection is set up with the bluetooth device (RN4678 module) after setting up the UART. The command mode of the RN4678 is used to connect it to the quadcopter.
void init_bt ()
Setup of the GPIO pins and Peripherable ports for the RN4678 module and initialize the RN4678.
Variables
UART_Handle uart
uint8_t ready_for_data = 0
Detailed Description
Author
Alexander Österreicher es19m008
Dennis Kwame Addo es19m006
Date
06.12.2019
More information about the project can be found here
See also
https://embsys.technikum-wien.at/mio/mes/1/esw/project/project.html#_documentation
Version
1.0
Definition in file RN4678.c.
Function Documentation
void init_bt ()
Parameters
void nothing
Returns
nothing but log and abort of failure to setup task for the BLUE Module
Definition at line 161 of file RN4678.c.
References RN4678_CTS, RN4678_CTS_PORT, RN4678_RTS, RN4678_RTS_PORT, RN4678Fxn(), RST, RST_PORT, STATUS1, STATUS1_PORT, STATUS2, STATUS2_PORT, SW_BTN, SW_BTN_PORT, U6RX, U6RX_PIN, U6TX, U6TX_PIN, U6TX_PORT, WAKEUP, and WAKEUP_PORT.
Referenced by main().
void RN4678Fxn (UArg arg0, UArg arg1)
Parameters
arg0 xdc data for passing commands to RTOS task
arg1 xdc data for passing commands to RTOS task
PNB: This is used in the CLI application
Returns
Nothing
Definition at line 89 of file RN4678.c.
References Board_UART6, ready_for_data, start_com(), STATUS1, STATUS1_PORT, STATUS2, STATUS2_PORT, and uart.
Referenced by init_bt().
void send_pac (char * data, size_t size)
Parameters
data Multiwii package in bytes to send.
size Total size of data to send.
Returns
Nothing
Definition at line 35 of file RN4678.c.
References RN4678_CTS, RN4678_CTS_PORT, RN4678_RTS, RN4678_RTS_PORT, and uart.
Referenced by set_flight_controls().
void start_com (char * cmd, uint8_t size, uint8_t retsize, char * input)
Parameters
cmd Command to send to the RN4678
size Total size of data to send.
retsize Total size of the return bytes (input data).
input Answer from the RN4678.
PNB: This is used in the CLI application
Returns
Nothing
Definition at line 59 of file RN4678.c.
References RN4678_CTS, RN4678_CTS_PORT, RN4678_RTS, RN4678_RTS_PORT, and uart.
Referenced by RN4678Fxn().
Variable Documentation
uint8_t ready_for_data = 0
ready_for_data Global 8 bit variable for signalling that the copter is ready for receiving data
Definition at line 23 of file RN4678.c.
Referenced by joystick_fnx(), and RN4678Fxn().
UART_Handle uart
uart Global UART handler for UART reading/writing
Definition at line 21 of file RN4678.c.
Referenced by RN4678Fxn(), send_pac(), and start_com().
Author
Generated automatically by Doxygen for copter_project from the source code.