RN4678.h
NAME
RN4678.h - The GPIO setup and data transfer functions for the RN4678 module.
SYNOPSIS
#include <Board.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <driverlib/gpio.h>
#include <driverlib/pin_map.h>
#include <driverlib/sysctl.h>
#include <driverlib/uart.h>
#include <inc/hw_memmap.h>
#include <ti/drivers/UART.h>
#include <ti/sysbios/knl/Task.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/System.h>
#include <xdc/std.h>
Macros
#define SW_BTN GPIO_PIN_2
#define SW_BTN_PORT GPIO_PORTD_BASE
#define RST GPIO_PIN_4
#define RST_PORT GPIO_PORTP_BASE
#define RN4678_RTS GPIO_PIN_5
#define RN4678_RTS_PORT GPIO_PORTP_BASE
#define RN4678_CTS GPIO_PIN_4
#define RN4678_CTS_PORT GPIO_PORTD_BASE
#define U6RX GPIO_PP0_U6RX
#define U6RX_PIN GPIO_PIN_0
#define U6RX_PORT GPIO_PORTP_BASE
#define U6TX GPIO_PP1_U6TX
#define U6TX_PIN GPIO_PIN_1
#define U6TX_PORT GPIO_PORTP_BASE
#define WAKEUP GPIO_PIN_7
#define WAKEUP_PORT GPIO_PORTM_BASE
#define STATUS1 GPIO_PIN_3
#define STATUS1_PORT GPIO_PORTQ_BASE
#define STATUS2 GPIO_PIN_0
#define STATUS2_PORT GPIO_PORTQ_BASE
Functions
void init_bt ()
Setup of the GPIO pins and Peripherable ports for the RN4678 module.
void send_pac (char *data, size_t size)
This is used to send Multiwii command to the quadcopter via bluetooth. The header and the command are packed in one packet of bytes. Activate the GPIO port for sending data check if port is ready and send data using UART write and wait till bytes is completely written and turnoff GPIO pin.
Detailed Description
Author
Alexander Österreicher es19m008
Dennis Kwame Addo es19m006
More information about the project can be found here
See also
https://embsys.technikum-wien.at/mio/mes/1/esw/project/project.html#_documentation
Date
06.12.2019
Version
1.0
Todo
All implentations must be contained in one method structure unless these functions @ are required by other programs/methods
Definition in file RN4678.h.
Macro Definition Documentation
#define RN4678_CTS GPIO_PIN_4
is RTS from TivaBoard
Definition at line 52 of file RN4678.h.
#define RN4678_CTS_PORT GPIO_PORTD_BASE
Definition at line 53 of file RN4678.h.
#define RN4678_RTS GPIO_PIN_5
is CTS from TivaBoard
Definition at line 50 of file RN4678.h.
#define RN4678_RTS_PORT GPIO_PORTP_BASE
Definition at line 51 of file RN4678.h.
#define RST GPIO_PIN_4
Definition at line 48 of file RN4678.h.
#define RST_PORT GPIO_PORTP_BASE
Definition at line 49 of file RN4678.h.
#define STATUS1 GPIO_PIN_3
Definition at line 62 of file RN4678.h.
#define STATUS1_PORT GPIO_PORTQ_BASE
Definition at line 63 of file RN4678.h.
#define STATUS2 GPIO_PIN_0
Definition at line 64 of file RN4678.h.
#define STATUS2_PORT GPIO_PORTQ_BASE
Definition at line 65 of file RN4678.h.
#define SW_BTN GPIO_PIN_2
--------------------------------------------------------------- defines --
Definition at line 46 of file RN4678.h.
#define SW_BTN_PORT GPIO_PORTD_BASE
Definition at line 47 of file RN4678.h.
#define U6RX GPIO_PP0_U6RX
Definition at line 54 of file RN4678.h.
#define U6RX_PIN GPIO_PIN_0
Definition at line 55 of file RN4678.h.
#define U6RX_PORT GPIO_PORTP_BASE
Definition at line 56 of file RN4678.h.
#define U6TX GPIO_PP1_U6TX
Definition at line 57 of file RN4678.h.
#define U6TX_PIN GPIO_PIN_1
Definition at line 58 of file RN4678.h.
#define U6TX_PORT GPIO_PORTP_BASE
Definition at line 59 of file RN4678.h.
#define WAKEUP GPIO_PIN_7
Definition at line 60 of file RN4678.h.
#define WAKEUP_PORT GPIO_PORTM_BASE
Definition at line 61 of file RN4678.h.
Function Documentation
void init_bt ()
Parameters
void nothing
Returns
nothing but log and abort of failure to setup task for the BLUE Module
Definition at line 165 of file RN4678.c.
References RN4678_CTS, RN4678_CTS_PORT, RN4678_RTS, RN4678_RTS_PORT, RN4678Fxn(), RST, RST_PORT, STATUS1, STATUS1_PORT, STATUS2, STATUS2_PORT, SW_BTN, SW_BTN_PORT, U6RX, U6RX_PIN, U6TX, U6TX_PIN, U6TX_PORT, WAKEUP, and WAKEUP_PORT.
Referenced by main().
void send_pac (char * data, size_t size)
Parameters
data Multiwii package in bytes to send.
size Total size of data to send.
Returns
Nothing
Definition at line 37 of file RN4678.c.
References RN4678_CTS, RN4678_CTS_PORT, RN4678_RTS, RN4678_RTS_PORT, and uart.
Referenced by set_flight_controls().
Author
Generated automatically by Doxygen for copter_project from the source code.