.TH "StartBIOS.c" 3 "Mon Jan 13 2020" "Version 1.0" "copter_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StartBIOS.c \- This is a simple quadcopter controller firmware\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <xdc/runtime/System\&.h>\fP
.br
\fC#include <ti/sysbios/BIOS\&.h>\fP
.br
\fC#include <Board\&.h>\fP
.br
\fC#include <RN4678\&.h>\fP
.br
\fC#include <TI_Joystick\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "The Entry point of the quadcopter application\&. Setting up board specific pins/GPIO init and setup the RN468 GPIO to kick up the BLUETH Modules( with RTOS task)\&. ADC initialization and setup of the task for Joystick data processing to feed to the quadcopter ver the BLUETH\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Alexander Österreicher es19m008 
.PP
Dennis Kwame Addo es19m006 
.RE
.PP
\fBDate\fP
.RS 4
06\&.12\&.2019
.RE
.PP
More information about the project can be found here 
.PP
\fBSee also\fP
.RS 4
https://embsys.technikum-wien.at/mio/mes/1/esw/project/project.html#_documentation
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBStartBIOS\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
\fBParameters\fP
.RS 4
\fIvoid\fP nothing 
.RE
.PP
\fBReturns\fP
.RS 4
Jump to RTOS tasks manager from BIOS and EXIT_FAILURE on failure (Error trap function) 
.RE
.PP

.PP
Definition at line 46 of file StartBIOS\&.c\&.
.PP
References Board_initGeneral, Board_initGPIO, EdM_ADC_Init(), init_bt(), and setUpJoyStick_Task()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copter_project from the source code\&.
