StartBIOS.c
NAME
StartBIOS.c - This is a simple quadcopter controller firmware.
SYNOPSIS
#include <xdc/runtime/System.h>
#include <ti/sysbios/BIOS.h>
#include <Board.h>
#include <RN4678.h>
#include <TI_Joystick.h>
Functions
int main (void)
The Entry point of the quadcopter application. Setting up board specific pins/GPIO init and setup the RN468 GPIO to kick up the BLUETH Modules( with RTOS task). ADC initialization and setup of the task for Joystick data processing to feed to the quadcopter ver the BLUETH.
Detailed Description
Author
Alexander Österreicher es19m008
Dennis Kwame Addo es19m006
Date
06.12.2019
More information about the project can be found here
See also
https://embsys.technikum-wien.at/mio/mes/1/esw/project/project.html#_documentation
Version
1.0
Definition in file StartBIOS.c.
Function Documentation
int main (void)
Parameters
void nothing
Returns
Jump to RTOS tasks manager from BIOS and EXIT_FAILURE on failure (Error trap function)
Definition at line 46 of file StartBIOS.c.
References Board_initGeneral, Board_initGPIO, EdM_ADC_Init(), init_bt(), and setUpJoyStick_Task().
Author
Generated automatically by Doxygen for copter_project from the source code.