TI_Joystick.h
NAME
TI_Joystick.h - Application for getting Joystick data, x y-axis ADC values, accelerometer and converting them to the right values for controlling the quadcopter.
SYNOPSIS
#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include 'inc/hw_memmap.h'
#include 'driverlib/gpio.h'
#include <ti/sysbios/knl/Mailbox.h>
#include <xdc/runtime/Error.h>
#include <ti/sysbios/knl/Event.h>
#include <RN4678.h>
Data Structures
struct raw_rc_frame
Macros
#define JOYS_GPIO_BASE GPIO_PORTE_BASE
#define JOYS_ADC_BASE ADC0_BASE
#define JOYS_TIMER_BASE TIMER0_BASE
#define JOYS_SAMPLE_RATE 4
#define JOYS_X GPIO_PIN_4
#define JOYS_Y GPIO_PIN_3
#define JOYS_CH_X ADC_CTL_CH9
#define JOYS_CH_Y ADC_CTL_CH0
#define JOyACC_X GPIO_PIN_0
#define JOyACC_Y GPIO_PIN_1
#define JOyACC_Z GPIO_PIN_2
#define JOyACC_ADC_BASE ADC1_BASE
#define JOyACC_CH_X ADC_CTL_CH3
#define JOyACC_CH_Y ADC_CTL_CH2
#define JOyACC_CH_Z ADC_CTL_CH1
Typedefs
typedef struct raw_rc_frame raw_rc_frame
Functions
void EdM_ADC_Init (void)
Set up the GPIO port and pins for the ADC driver which is used to read the ADC value for the x, y-axis, and accelerometer values of the EDUMIKI Joystick controller.
void setUpJoyStick_Task ()
Set up task for the Joystick controller with the hight task priority for fast pulling of the ADC values.
void initSPI (void)
void send_to_Screen (char data)
Detailed Description
Author
Alexander Österreicher es19m008
Dennis Kwame Addo es19m006
More information about the project can be found here
See also
https://embsys.technikum-wien.at/mio/mes/1/esw/project/project.html#_documentation
Date
18.12.2019
Version
1.0
Todo
All implentations must be contained in one method structure unless these functions @ are required by other programs/methods
Definition in file TI_Joystick.h.
Macro Definition Documentation
#define JOyACC_ADC_BASE ADC1_BASE
Definition at line 70 of file TI_Joystick.h.
#define JOyACC_CH_X ADC_CTL_CH3
Definition at line 72 of file TI_Joystick.h.
#define JOyACC_CH_Y ADC_CTL_CH2
Definition at line 73 of file TI_Joystick.h.
#define JOyACC_CH_Z ADC_CTL_CH1
Definition at line 74 of file TI_Joystick.h.
#define JOyACC_X GPIO_PIN_0
Definition at line 66 of file TI_Joystick.h.
#define JOyACC_Y GPIO_PIN_1
Definition at line 67 of file TI_Joystick.h.
#define JOyACC_Z GPIO_PIN_2
Definition at line 68 of file TI_Joystick.h.
#define JOYS_ADC_BASE ADC0_BASE
Definition at line 55 of file TI_Joystick.h.
#define JOYS_CH_X ADC_CTL_CH9
Definition at line 62 of file TI_Joystick.h.
#define JOYS_CH_Y ADC_CTL_CH0
Definition at line 63 of file TI_Joystick.h.
#define JOYS_GPIO_BASE GPIO_PORTE_BASE
--------------------------------------------------------------- defines --
Definition at line 54 of file TI_Joystick.h.
#define JOYS_SAMPLE_RATE 4
Definition at line 58 of file TI_Joystick.h.
#define JOYS_TIMER_BASE TIMER0_BASE
Definition at line 56 of file TI_Joystick.h.
#define JOYS_X GPIO_PIN_4
Definition at line 60 of file TI_Joystick.h.
#define JOYS_Y GPIO_PIN_3
Definition at line 61 of file TI_Joystick.h.
Typedef Documentation
raw_rc_frame
Function Documentation
void EdM_ADC_Init (void)
Parameters
void nothing
Returns
Definition at line 98 of file TI_Joystick.c.
References Board_EduMIKI_SEL, gpioSeLFxn0(), JOyACC_ADC_BASE, JOyACC_CH_X, JOyACC_CH_Y, JOyACC_CH_Z, JOyACC_X, JOyACC_Y, JOyACC_Z, JOYS_ADC_BASE, JOYS_CH_X, JOYS_CH_Y, JOYS_GPIO_BASE, JOYS_X, and JOYS_Y.
Referenced by main().
void initSPI (void)
void send_to_Screen (char data)
void setUpJoyStick_Task (void)
Parameters
void nothing
Returns
Definition at line 145 of file TI_Joystick.c.
References joystick_fnx().
Referenced by main().
Author
Generated automatically by Doxygen for copter_project from the source code.