TI_Joystick.c
NAME
TI_Joystick.c - Application for getting Joystick data, x y-axis ADC values, accelerometer and converting them to the right values for controlling the quadcopter.
SYNOPSIS
#include <TI_Joystick.h>
#include 'driverlib/debug.h'
#include 'driverlib/sysctl.h'
#include 'inc/hw_types.h'
#include 'driverlib/adc.h'
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Task.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include 'inc/hw_memmap.h'
#include 'driverlib/gpio.h'
#include <ti/drivers/GPIO.h>
#include <Board.h>
Functions
void joystick_fnx (UArg arg0)
This is the joystick RTOS task, also used for processing Joystick and accelerometer data. The ADC values needs to be processed to limit input signal to the upper and lower saturation values. set_flight_controls is then called to get data to the quadcopter by sending payload to the quadcopter via the send_pac function.
void set_flight_controls ()
Create a multi-wii packet from the controller values to control the quadcopter. send the payload to quadcopter via the Bluetooth module.
void arm ()
To start the quadcopter spinning.
void disarm ()
To stop the quadcopter spinning.
void gpioSeLFxn0 (unsigned int index)
This is Joystick middle button. Using simple Interrupt for arm and disarm function.
void EdM_ADC_Init (void)
Set up the GPIO port and pins for the ADC driver which is used to read the ADC value for the x, y-axis, and accelerometer values of the EDUMIKI Joystick controller.
void setUpJoyStick_Task (void)
Set up task for the Joystick controller with the hight task priority for fast pulling of the ADC values.
Variables
raw_rc_frame frame
uint8_t ready_for_data
Detailed Description
Author
Alexander Österreicher es19m008
Dennis Kwame Addo es19m006
Date
18.12.2019
More information about the project can be found here
See also
https://embsys.technikum-wien.at/mio/mes/1/esw/project/project.html#_documentation
Version
1.0
Definition in file TI_Joystick.c.
Function Documentation
void arm ()
Parameters
void nothing
Returns
Definition at line 284 of file TI_Joystick.c.
References raw_rc_frame::arm, and frame.
void disarm ()
Parameters
void nothing
Returns
Definition at line 302 of file TI_Joystick.c.
References raw_rc_frame::arm, and frame.
void EdM_ADC_Init (void)
Parameters
void nothing
Returns
Definition at line 98 of file TI_Joystick.c.
References Board_EduMIKI_SEL, gpioSeLFxn0(), JOyACC_ADC_BASE, JOyACC_CH_X, JOyACC_CH_Y, JOyACC_CH_Z, JOyACC_X, JOyACC_Y, JOyACC_Z, JOYS_ADC_BASE, JOYS_CH_X, JOYS_CH_Y, JOYS_GPIO_BASE, JOYS_X, and JOYS_Y.
Referenced by main().
void gpioSeLFxn0 (unsigned int index)
Parameters
index the button ID
PNB:
Returns
Nothing
Definition at line 69 of file TI_Joystick.c.
Referenced by EdM_ADC_Init().
void joystick_fnx (UArg arg0)
Parameters
arg0 xdc argument to the RTOS task.
PNB:
Returns
Nothing
Definition at line 179 of file TI_Joystick.c.
References raw_rc_frame::azimuth, frame, JOyACC_ADC_BASE, raw_rc_frame::pitch, ready_for_data, raw_rc_frame::roll, set_flight_controls(), and raw_rc_frame::throttle.
Referenced by setUpJoyStick_Task().
void set_flight_controls ()
Parameters
void nothing
Returns
Definition at line 321 of file TI_Joystick.c.
References raw_rc_frame::arm, raw_rc_frame::azimuth, frame, raw_rc_frame::pitch, raw_rc_frame::roll, send_pac(), and raw_rc_frame::throttle.
Referenced by joystick_fnx().
void setUpJoyStick_Task (void)
Parameters
void nothing
Returns
Definition at line 145 of file TI_Joystick.c.
References joystick_fnx().
Referenced by main().
Variable Documentation
raw_rc_frame frame
Definition at line 49 of file TI_Joystick.c.
Referenced by arm(), disarm(), joystick_fnx(), and set_flight_controls().
uint8_t ready_for_data
ready_for_data Global 8 bit variable for controlling the data transfer
Definition at line 23 of file RN4678.c.
Referenced by joystick_fnx(), and RN4678Fxn().
Author
Generated automatically by Doxygen for copter_project from the source code.