.TH "todo" 3 "Mon Jan 13 2020" "Version 1.0" "copter_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBFile \fBRN4678\&.h\fP \fP" 1c
All implentations must be contained in one method structure unless these functions @ are required by other programs/methods 
.IP "\fBFile \fBTI_Joystick\&.h\fP \fP" 1c
All implentations must be contained in one method structure unless these functions @ are required by other programs/methods
.PP

